//------------------------------------
// ENVIRONMENT book
//
// Template for requirement:
//[[ex-keyword]] 
//`{counter:environment}`
// Requirement

// {missing} [Corresponding Artifact]
//------------------------------------
== Environment

=== E.1 Glossary

This section defines the domain-specific terms used in this document.

It also lists the icons used in this document.

[[e1-terms]]
==== `E.1.{counter:e1}` Terms

[[companion]]
{companion}:: The _system_ to be developed: the companion book of {Handbook}. Current version available {companionURL}[here].

[[Handbook]]
{Handbook}:: The book, entitled "Handbook of requirements and business analysis", written by Bertrand Meyer (see PDF {HandbookPDF}[here]), and for which the {companion} serves as complementary material.

==== `E.1.{counter:e1}` Icons

Here is the list of significations for the icons used when tracing the corresponding artifacts:

//----------------------------------------------
.Icons signification
[cols="1,7",options="header"]
|===
| Icon | Signification
//----------------------------------------------
| {check}  | A precisely referenced artifact satisfying the requirement
| {bug}    | An artifact not yet fully functional
| {missing}| No corresponding artifact yet (requirement not satisfied)
|=== 
//----------------------------------------------

=== E.2 Components

{emptysec}

=== E.3 Constraints

:e3-method: {counter:e3}
[[e3-method]]
`E.3.{e3-method}`
The {companion} should itself apply the method described in the {Handbook}. 

:e3-pages: {counter:e3}
[[e3-pages]]
`E.3.{e3-pages}` 
//From an email by Springer's contact on August, 2nd 2023.
The {companion} should reach at least 160-170 pages.

:e3-pages-rational:  {counter:e3}
[[e3-pages-rational]]
`E.3.{e3-pages-rational}` 
The rational for requirement <<e3-pages,E.3.{e3-pages}>> is: in order to have a sufficient distinction from the https://www.springer.com/series/10028[SpringerBriefs].

=== E.4 Assumptions

:e4-review: {counter:e4}
[[e4-review]]
`E.4.{e4-review}`
The {companion} will be reviewed by the author of the {Handbook}. 

=== E.5 Effects

{emptysec}

=== E.6 Invariants

{emptysec}
